# Generated by Django 5.1.7 on 2025-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_comment_post_alter_commentlike_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='story_videos/'),
        ),
    ]
